// Fiche de chaque champion pour l'analyse de draft : 'dégâts scaling traits'
//
// Dégâts : P = physiques, M = magiques, X = mixtes
// Scaling : e = early, m = mid game, l = late game
// Traits :
//   F = frontline (encaisse)      E = engage (lance les fights)
//   C = contrôle fiable (CC)      K = poke / siège
//   A = pick / burst (assassin)   S = split push / side lane
//   D = DPS en teamfight          P = peel / protection, disengage
//
// Les champions absents de la liste (ex : sortis récemment) sont estimés via les tags Riot.
// N'hésitez pas à corriger une fiche si vous n'êtes pas d'accord !
export const PROFILES = {
  Aatrox: 'P m FSD',
  Ahri: 'M m AC',
  Akali: 'M m AS',
  Akshan: 'P m AS',
  Alistar: 'M e FECP',
  Ambessa: 'P m SA',
  Amumu: 'M m FEC',
  Anivia: 'M l CKP',
  Annie: 'M m EC',
  Aphelios: 'P l D',
  Ashe: 'P m DC',
  AurelionSol: 'M l DK',
  Aurora: 'M m AC',
  Azir: 'M l DK',
  Bard: 'M m CP',
  Belveth: 'P l SD',
  Blitzcrank: 'M e CA',
  Brand: 'M m KD',
  Braum: 'M m FPC',
  Briar: 'P e AD',
  Caitlyn: 'P e KD',
  Camille: 'P m SAE',
  Cassiopeia: 'M l DC',
  Chogath: 'M m FC',
  Corki: 'X m KD',
  Darius: 'P e FD',
  Diana: 'M m EA',
  DrMundo: 'P l FS',
  Draven: 'P e D',
  Ekko: 'M m AS',
  Elise: 'M e AC',
  Evelynn: 'M m A',
  Ezreal: 'P m KD',
  Fiddlesticks: 'M m EC',
  Fiora: 'P l S',
  Fizz: 'M m A',
  Galio: 'M m FECP',
  Gangplank: 'P l SK',
  Garen: 'P e FS',
  Gnar: 'P m FECS',
  Gragas: 'M m FECP',
  Graves: 'P m D',
  Gwen: 'M m DS',
  Hecarim: 'P m FE',
  Heimerdinger: 'M m K',
  Hwei: 'M m KC',
  Illaoi: 'P m FS',
  Irelia: 'P m SD',
  Ivern: 'M m P',
  Janna: 'M m P',
  JarvanIV: 'P e FEC',
  Jax: 'P l SF',
  Jayce: 'P e KS',
  Jhin: 'P m KC',
  Jinx: 'P l D',
  Kaisa: 'X l DA',
  Kalista: 'P e D',
  Karma: 'M e KP',
  Karthus: 'M l D',
  Kassadin: 'M l A',
  Katarina: 'M m A',
  Kayle: 'X l D',
  Kayn: 'P m A',
  Kennen: 'M m EC',
  Khazix: 'P m A',
  Kindred: 'P l D',
  Kled: 'P e FE',
  KogMaw: 'X l D',
  KSante: 'P m FEC',
  Leblanc: 'M m A',
  LeeSin: 'P e AE',
  Leona: 'M e FEC',
  Lillia: 'M m DC',
  Lissandra: 'M m EC',
  Lucian: 'P e D',
  Lulu: 'M m P',
  Lux: 'M m KC',
  Malphite: 'M m FEC',
  Malzahar: 'M m C',
  Maokai: 'M m FEC',
  MasterYi: 'P l DS',
  Mel: 'M m K',
  Milio: 'M m P',
  MissFortune: 'P m D',
  MonkeyKing: 'P m ES',
  Mordekaiser: 'M m FS',
  Morgana: 'M m CP',
  Naafiri: 'P e A',
  Nami: 'M m CP',
  Nasus: 'P l FS',
  Nautilus: 'M e FEC',
  Neeko: 'M m EC',
  Nidalee: 'M e KA',
  Nilah: 'P l D',
  Nocturne: 'P m EA',
  Nunu: 'M m FEC',
  Olaf: 'P e FD',
  Orianna: 'M m DC',
  Ornn: 'M l FEC',
  Pantheon: 'P e AE',
  Poppy: 'P m FCP',
  Pyke: 'P e AC',
  Qiyana: 'P m AC',
  Quinn: 'P e AS',
  Rakan: 'M m EC',
  Rammus: 'M m FEC',
  RekSai: 'P e E',
  Rell: 'M m FEC',
  Renata: 'M m PC',
  Renekton: 'P e FS',
  Rengar: 'P m A',
  Riven: 'P m SA',
  Rumble: 'M m D',
  Ryze: 'M l D',
  Samira: 'P m D',
  Sejuani: 'M m FEC',
  Senna: 'P l KP',
  Seraphine: 'M m PK',
  Sett: 'P e FE',
  Shaco: 'P e A',
  Shen: 'M m FEP',
  Shyvana: 'M m FD',
  Singed: 'M m FS',
  Sion: 'P m FEC',
  Sivir: 'P m D',
  Skarner: 'P m FEC',
  Smolder: 'P l D',
  Sona: 'M l P',
  Soraka: 'M m P',
  Swain: 'M m FD',
  Sylas: 'M m A',
  Syndra: 'M m AC',
  TahmKench: 'M m FP',
  Taliyah: 'M m C',
  Talon: 'P e A',
  Taric: 'M m FP',
  Teemo: 'M m KS',
  Thresh: 'M m CP',
  Tristana: 'P l D',
  Trundle: 'P m FS',
  Tryndamere: 'P l S',
  TwistedFate: 'M m AS',
  Twitch: 'P l D',
  Udyr: 'X m FS',
  Urgot: 'P m FS',
  Varus: 'P m KC',
  Vayne: 'P l D',
  Veigar: 'M l AC',
  Velkoz: 'M m K',
  Vex: 'M m AC',
  Vi: 'P e EA',
  Viego: 'P m DA',
  Viktor: 'M l DK',
  Vladimir: 'M l D',
  Volibear: 'X e FE',
  Warwick: 'X e F',
  Xayah: 'P m D',
  Xerath: 'M m K',
  XinZhao: 'P e E',
  Yasuo: 'P m D',
  Yone: 'X m D',
  Yorick: 'P m S',
  Yuumi: 'M m P',
  Zac: 'M m FEC',
  Zed: 'P m A',
  Zeri: 'P l D',
  Ziggs: 'M m K',
  Zilean: 'M m PK',
  Zoe: 'M m KA',
  Zyra: 'M m KC',
}

// Estimation à partir des tags Data Dragon pour les champions sans fiche.
const TAG_TRAITS = {
  Tank: 'FEC',
  Fighter: 'FS',
  Assassin: 'A',
  Mage: 'K',
  Marksman: 'D',
  Support: 'P',
}

export function getProfile(champ) {
  const raw = PROFILES[champ.id]
  if (raw) {
    const [damage, scaling, traits = ''] = raw.split(' ')
    return { damage, scaling, traits: new Set(traits), estimated: false }
  }
  const traits = new Set((champ.tags ?? []).flatMap((t) => [...(TAG_TRAITS[t] ?? '')]))
  const damage = (champ.info?.magic ?? 0) > (champ.info?.attack ?? 0) ? 'M' : 'P'
  const scaling = champ.tags?.includes('Marksman') ? 'l' : 'm'
  return { damage, scaling, traits, estimated: true }
}
